version: '3.8'
services:
  backend:
    build: ./docnow-backend
    image: docnow/backend:latest
    ports: ["8080:8080"]
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/docnow

  jee:
    build: ./docnow-jee
    image: docnow/jee:latest
    ports: ["8081:8080"]

  frontend:
    build: ./docnow-frontend
    image: docnow/frontend:latest
    ports: ["80:80"]

  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
