name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run tests and build Spring Boot backend
        working-directory: docnow-backend
        run: mvn clean verify
      - name: Générer le rapport HTML des tests backend
        working-directory: docnow-backend
        run: mvn surefire-report:report
      - name: Upload test report (TXT/XML)
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: docnow-backend/target/surefire-reports/
      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: backend-html-report
          path: docnow-backend/target/site/surefire-report.html
      - name: Build Spring Boot backend (package)
        working-directory: docnow-backend
        run: mvn package -DskipTests

  build-jee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run tests and build JEE application
        working-directory: docnow-jee
        run: mvn clean verify
      - name: Générer le rapport HTML des tests JEE
        working-directory: docnow-jee
        run: mvn surefire-report:report
      - name: Upload test report (TXT/XML)
        uses: actions/upload-artifact@v4
        with:
          name: jee-test-report
          path: docnow-jee/target/surefire-reports/
      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: jee-html-report
          path: docnow-jee/target/site/surefire-report.html
      - name: Build JEE application (package)
        working-directory: docnow-jee
        run: mvn package -DskipTests

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ≥18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: docnow-frontend
        run: npm install
      - name: Run frontend tests
        working-directory: docnow-frontend
        run: npm test -- --ci --reporters=default --reporters=jest-junit
      - name: Upload Jest JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-junit-report
          path: docnow-frontend/junit.xml

  build-frontend:
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ≥18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install & build frontend
        working-directory: docnow-frontend
        run: |
            npm install
            npm run build

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ≥18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build frontend
        working-directory: docnow-frontend
        run: |
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docnow-frontend/dist

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy backend JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docnow-backend/target/*.jar"
          target: "/opt/docnow-backend/"
      - name: Lancer le backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /opt/docnow-backend/*.jar > /opt/docnow-backend/app.log 2>&1 &

  deploy-jee:
    needs: build-jee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy JEE WAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docnow-jee/target/*.war"
          target: "/opt/tomcat10/webapps/"
      - name: Redémarrer Tomcat
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            /opt/tomcat10/bin/shutdown.sh || true
            /opt/tomcat10/bin/startup.sh
